version: "3.3"
services:
  db:
    image: mysql:8.0
    container_name: db
    restart: unless-stopped
    ports:
      - "3306:3306"
    env_file: ../conf/mysql_env
    volumes:
      - db_data:/var/lib/mysql
    networks:
      app_network:
        aliases:
          - app_network
    
  web:
    depends_on:
    - db
    container_name: web
    restart: always
    build:
      context: ../
      dockerfile: ./docker/Dockerfile
    ports:
      - "5000:5000"
    volumes:
      - ../../personal_website:/personal_website
    networks:
      app_network:
        aliases:
          - app_network

  # nginx:
  #   depends_on:
  #     - web
  #   image: nginx
  #   container_name: nginx
  #   restart: always
  #   ports:
  #     - "80:80"
  #     - "443:443"
  #   volumes:
  #     - ../nginx/nginx.conf:/etc/nginx/nginx.conf
  #     - /etc/letsencrypt/:/etc/letsencrypt/
  #   networks:
  #     app_network:
  #       aliases:
  #         - app_network

volumes:
  db_data:

networks:
    app_network:

  


