version: "3.3"
services:
  web:
      container_name: web
      restart: always
      build:
        context: ./
        dockerfile: ./Dockerfile
      ports:
        - "5000:5000"
      volumes:
        - ../../personal_website:/personal_website
      networks:
        app_network:
          aliases:
            - app_network
  nginx:
      depends_on:
        - web
      image: nginx
      container_name: nginx
      restart: always
      ports:
        - "80:80"
        - "443:443"
      volumes:
        - ../nginx_conf/nginx.conf:/etc/nginx/nginx.conf
      networks:
        app_network:
          aliases:
            - app_network


networks:
    app_network:

  


